# Generated by Django 5.1.2 on 2024-11-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_image_alter_product_merek_produk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='merek_produk',
            field=models.CharField(choices=[('waisted Jeans', 'waisted Jeans'), ('O&B', 'O&B'), ('Ae-Ri', 'Ae-Ri'), ('Dore', 'Dore'), ('SureDesign', 'SureDesign'), ('Walnuts', 'Walnuts')], max_length=30),
        ),
    ]
