# Generated by Django 5.1.2 on 2024-11-11 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birth_date',
            new_name='birthdate',
        ),
    ]
